##
## Basic Options
##

set -g default-command /bin/zsh
set -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "screen-256color"
set-option -g renumber-windows on
set-option -g status-interval 1
set-option -g automatic-rename on

# Mouse
set -g mouse on
if-shell 'command -v wl-copy' {
    bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"
}
# Enable mouse scroll, see https://github.com/tmux/tmux/issues/145#issuecomment-150736967
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

# Fix terminal name issues
set -s escape-time 1

##
## Key bindings
##

# Reload the tmux config.
unbind r
bind-key r source-file ~/.tmux.conf

# Use ctrl + left/right arrow to switch to prev/next window
bind-key -n C-M-Left previous-window # change window with ctrl-left
bind-key -n C-M-Right next-window # change window with ctrl-right

# Resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r M resize-pane -Z

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Split window
unbind %
bind-key v split-window -h -c "#{pane_current_path}"
unbind '"'
bind-key h split-window -v -c "#{pane_current_path}"

# Sync panes
bind-key u setw synchronize-panes

##
## Appearance
##

##
## Plugins
##

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'odedlaz/tmux-onedark-theme'

# Theme
set -g @onedark_date_format "%d.%m.%Y"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
